import { useSuspenseQuery, useQueryClient } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { MapPin, Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { addressesQuery } from "@/lib/account-queries";
import { addMyAddress, deleteMyAddress } from "@/lib/account.functions";

export const Route = createFileRoute("/account/addresses")({ loader: ({ context }) => context.queryClient.ensureQueryData(addressesQuery), component: Addresses });
type AddressForm = { label: string; recipient_name: string; phone: string; line1: string; line2: string; city: string; state: string; postal_code: string; country: string; is_default: boolean };
const blank = (): AddressForm => ({ label: "", recipient_name: "", phone: "", line1: "", line2: "", city: "", state: "", postal_code: "", country: "Nigeria", is_default: false });

function Addresses() {
  const { data: addresses } = useSuspenseQuery(addressesQuery);
  const queryClient = useQueryClient();
  const [form, setForm] = useState<AddressForm>(blank());
  const [open, setOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const refresh = () => queryClient.invalidateQueries({ queryKey: ["account", "addresses"] });
  return <div className="space-y-5"><header className="flex flex-col gap-4 border-b border-border pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Delivery</p><h1 className="mt-1 text-2xl font-semibold text-ivory">Addresses</h1><p className="mt-1 text-sm text-grey">Saved addresses for a faster checkout.</p></div><button type="button" onClick={() => { setOpen((value) => !value); setError(null); }} className="inline-flex items-center gap-2 rounded-md border border-border bg-card px-3 py-2 text-sm font-medium text-ivory hover:bg-bg-soft"><Plus className="size-4" />Add address</button></header>
    {open ? <form className="grid gap-4 rounded-lg border border-border bg-card p-5" onSubmit={async (event) => { event.preventDefault(); setSaving(true); setError(null); try { await addMyAddress({ data: form }); setForm(blank()); setOpen(false); await refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Address could not be saved."); } finally { setSaving(false); } }}><div className="flex items-center justify-between"><h2 className="font-semibold text-ivory">New address</h2><button type="button" onClick={() => setOpen(false)} className="text-sm text-grey hover:text-ivory">Cancel</button></div>{error ? <p className="rounded border border-red-500/30 bg-red-500/10 px-3 py-2 text-sm text-red-700 dark:text-red-300">{error}</p> : null}<div className="grid gap-4 sm:grid-cols-2"><Field label="Label" value={form.label} onChange={(value) => setForm((current) => ({ ...current, label: value }))} placeholder="Home, Office" /><Field label="Recipient name" value={form.recipient_name} onChange={(value) => setForm((current) => ({ ...current, recipient_name: value }))} required /><Field label="Phone" value={form.phone} onChange={(value) => setForm((current) => ({ ...current, phone: value }))} /><Field label="Address line 1" value={form.line1} onChange={(value) => setForm((current) => ({ ...current, line1: value }))} required /><Field label="Address line 2" value={form.line2} onChange={(value) => setForm((current) => ({ ...current, line2: value }))} /><Field label="City" value={form.city} onChange={(value) => setForm((current) => ({ ...current, city: value }))} required /><Field label="State" value={form.state} onChange={(value) => setForm((current) => ({ ...current, state: value }))} required /><Field label="Postal code" value={form.postal_code} onChange={(value) => setForm((current) => ({ ...current, postal_code: value }))} /><Field label="Country" value={form.country} onChange={(value) => setForm((current) => ({ ...current, country: value }))} required /></div><label className="flex items-center gap-2 text-sm text-grey"><input type="checkbox" checked={form.is_default} onChange={(event) => setForm((current) => ({ ...current, is_default: event.target.checked }))} className="size-4 accent-[#c9a05c]" />Set as default address</label><button disabled={saving} className="justify-self-start rounded-md bg-foreground px-4 py-2 text-sm font-medium text-background disabled:opacity-50">{saving ? "Saving..." : "Save address"}</button></form> : null}
    {addresses.length === 0 ? <div className="rounded-lg border border-dashed border-border bg-bg-soft px-5 py-12 text-center"><MapPin className="mx-auto size-6 text-grey" /><p className="mt-3 font-medium text-ivory">No saved addresses</p><p className="mt-1 text-sm text-grey">Add one now to speed up your next order.</p></div> : <div className="grid gap-4 md:grid-cols-2">{addresses.map((address: any) => <article key={address.id} className="rounded-lg border border-border bg-card p-5"><div className="flex items-start justify-between gap-4"><div><p className="font-medium text-ivory">{address.label || "Delivery address"}{address.is_default ? <span className="ml-2 rounded-full bg-bg-soft px-2 py-0.5 text-xs text-grey">Default</span> : null}</p><p className="mt-3 text-sm text-grey">{address.recipient_name}</p><p className="mt-1 text-sm text-grey">{address.line1}{address.line2 ? `, ${address.line2}` : ""}</p><p className="mt-1 text-sm text-grey">{address.city}, {address.state} {address.postal_code}</p><p className="mt-1 text-sm text-grey">{address.country}{address.phone ? ` · ${address.phone}` : ""}</p></div><button type="button" onClick={async () => { if (!confirm("Delete this saved address?")) return; await deleteMyAddress({ data: { id: address.id } }); await refresh(); }} className="rounded p-1.5 text-grey hover:bg-red-500/10 hover:text-red-600" aria-label="Delete address"><Trash2 className="size-4" /></button></div></article>)}</div>}
  </div>;
}

function Field({ label, value, onChange, placeholder, required = false }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; required?: boolean }) { return <label className="grid gap-1.5"><span className="text-sm text-grey">{label}</span><input required={required} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} className="rounded border border-input bg-card px-3 py-2 text-sm text-ivory outline-none placeholder:text-grey-dim focus:border-gold" /></label>; }
